/* Generated by cbindgen — do not edit. */

#ifndef CALLBOOK_H
#define CALLBOOK_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>

/**
 * Return code: callsign was not found.
 */
#define CALLBOOK_E_NOT_FOUND -1

/**
 * Return code: invalid argument supplied by the caller.
 */
#define CALLBOOK_E_USAGE -2

/**
 * Return code: failed to open the database.
 */
#define CALLBOOK_E_OPEN_FAILED -3

/**
 * Return code: output buffer was too small for the result.
 */
#define CALLBOOK_E_BUFFER_TOO_SMALL -4

/**
 * Source flag: current US FCC catalog contributed to a snapshot.
 */
#define CALLBOOK_SOURCE_US_CSV (1 << 0)

/**
 * Source flag: direct `hamcall.idx` -> `hamcall.dat` lookup contributed.
 */
#define CALLBOOK_SOURCE_HAMCALL_DAT_IDX (1 << 1)

/**
 * Source flag: `hciindex.dat`/`hci.dat` lookup contributed.
 */
#define CALLBOOK_SOURCE_HAMCALL_HCI (1 << 2)

/**
 * Sidecar asset kind.
 */
typedef enum callbook_asset_kind {
  callbook_asset_kind_Biography = 0,
  callbook_asset_kind_Photo = 1,
  callbook_asset_kind_Flag = 2,
  callbook_asset_kind_Map = 3,
  callbook_asset_kind_SidecarData = 4,
} callbook_asset_kind;

/**
 * Source sidecar for country metadata.
 */
typedef enum callbook_country_source {
  callbook_country_source_Unknown = 0,
  callbook_country_source_Countrys = 1,
  callbook_country_source_GcMcountrys = 2,
  callbook_country_source_CountrysPc = 3,
} callbook_country_source;

/**
 * Country/jurisdiction classification.
 */
typedef enum callbook_jurisdiction {
  callbook_jurisdiction_UnitedStates = 0,
  callbook_jurisdiction_Canada = 1,
  callbook_jurisdiction_International = 2,
  callbook_jurisdiction_Unknown = 3,
} callbook_jurisdiction;

/**
 * High-level lookup status.
 */
typedef enum callbook_lookup_status {
  callbook_lookup_status_Current = 0,
  callbook_lookup_status_ArchiveOnly = 1,
  callbook_lookup_status_NotFound = 2,
} callbook_lookup_status;

/**
 * Field selector for [`callbook_snapshot_field`].
 */
typedef enum callbook_modern_field {
  callbook_modern_field_Callsign = 0,
  callbook_modern_field_Name = 1,
  callbook_modern_field_FirstName = 2,
  callbook_modern_field_MiddleName = 3,
  callbook_modern_field_LastName = 4,
  callbook_modern_field_Suffix = 5,
  callbook_modern_field_Address = 6,
  callbook_modern_field_City = 7,
  callbook_modern_field_StateOrProvince = 8,
  callbook_modern_field_PostalCode = 9,
  callbook_modern_field_County = 10,
  callbook_modern_field_Country = 11,
  callbook_modern_field_LicenseClass = 12,
  callbook_modern_field_RecordCode = 13,
  callbook_modern_field_BirthDate = 14,
  callbook_modern_field_FirstIssued = 15,
  callbook_modern_field_Expires = 16,
  callbook_modern_field_LastChanged = 17,
  callbook_modern_field_GmtOffset = 18,
  callbook_modern_field_Latitude = 19,
  callbook_modern_field_Longitude = 20,
  callbook_modern_field_Grid = 21,
  callbook_modern_field_AreaCode = 22,
  callbook_modern_field_PreviousCall = 23,
  callbook_modern_field_PreviousClass = 24,
  callbook_modern_field_FccTransactionType = 25,
  callbook_modern_field_Email = 26,
  callbook_modern_field_Qsl = 27,
  callbook_modern_field_Url = 28,
  callbook_modern_field_Interests = 29,
  callbook_modern_field_LicenseId = 30,
  callbook_modern_field_Frn = 31,
  callbook_modern_field_NumericId = 32,
  callbook_modern_field_FaxNumber = 33,
  callbook_modern_field_Iota = 34,
} callbook_modern_field;

/**
 * Field selector for [`callbook_us_record_field`].
 */
typedef enum callbook_us_field {
  callbook_us_field_Callsign = 0,
  callbook_us_field_Class = 1,
  callbook_us_field_Name = 2,
  callbook_us_field_Address = 3,
  callbook_us_field_City = 4,
  callbook_us_field_State = 5,
  callbook_us_field_Zip = 6,
  callbook_us_field_County = 7,
  callbook_us_field_LicenseIssueDate = 8,
  callbook_us_field_FccTransactionType = 9,
} callbook_us_field;

/**
 * Opaque sidecar asset metadata.
 */
typedef struct callbook_asset callbook_asset;

/**
 * Opaque owned country catalog snapshot.
 */
typedef struct callbook_country_catalog callbook_country_catalog;

/**
 * Opaque country metadata.
 */
typedef struct callbook_country_info callbook_country_info;

/**
 * Opaque handle returned by [`callbook_open`].
 *
 * Read-only after construction. Pointers handed out by [`callbook_open`]
 * can be shared across threads — the underlying [`CallBook`] supports
 * lock-free concurrent reads. Callers must not call [`callbook_close`] until
 * all concurrent calls using the handle have returned.
 */
typedef struct callbook_db callbook_db;

/**
 * Opaque interest item borrowed from a [`callbook_snapshot`].
 */
typedef struct callbook_interest callbook_interest;

/**
 * Opaque owned interest catalog definition.
 */
typedef struct callbook_interest_definition callbook_interest_definition;

/**
 * Opaque interest-search match.
 */
typedef struct callbook_interest_search_match callbook_interest_search_match;

/**
 * Opaque owned interest-search result.
 */
typedef struct callbook_interest_search_result callbook_interest_search_result;

/**
 * Opaque `counts.dat` lookup-count record.
 */
typedef struct callbook_lookup_count callbook_lookup_count;

/**
 * Opaque owned lookup-count catalog snapshot.
 */
typedef struct callbook_lookup_counts_catalog callbook_lookup_counts_catalog;

/**
 * Opaque owned result returned by [`callbook_lookup_modern`].
 *
 * All strings returned by result/snapshot accessors are borrowed from this
 * object and remain valid until [`callbook_result_free`] is called.
 */
typedef struct callbook_lookup_result callbook_lookup_result;

/**
 * Opaque owned station profile returned by [`callbook_profile_for_callsign`].
 *
 * Snapshot, country, count, and asset pointers borrowed from this object are
 * valid until [`callbook_profile_free`] is called.
 */
typedef struct callbook_profile callbook_profile;

/**
 * Opaque snapshot borrowed from a [`callbook_lookup_result`].
 *
 * Pointers to snapshots are invalidated when their owning result is freed.
 */
typedef struct callbook_snapshot callbook_snapshot;

/**
 * Opaque current-US catalog record.
 */
typedef struct callbook_us_record callbook_us_record;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Open a local Buckmaster HamCall database tree at `data_path`.
 *
 * On success returns 0 and writes a non-null pointer into `*out`. On
 * failure returns one of the documented negative codes and writes null.
 *
 * # Safety
 *
 * `data_path` must be a valid NUL-terminated UTF-8 C string. `out` must be
 * a writable pointer to `*mut callbook_db`.
 */
int callbook_open(const char *data_path, struct callbook_db **out);

/**
 * Close a database opened by [`callbook_open`]. Safe to pass null.
 *
 * Do not close a handle while another thread is using it.
 *
 * # Safety
 *
 * `db` must be a pointer returned by [`callbook_open`] and not yet closed.
 */
void callbook_close(struct callbook_db *db);

/**
 * Look up `callsign` in the structured lookup path.
 *
 * This function uses the database handle opened by [`callbook_open`]; it does
 * not rescan or reopen the database. On success, it writes an owned result to
 * `*out` and returns 0. A not-found callsign is still a successful lookup:
 * inspect [`callbook_result_status`] for [`callbook_lookup_status::NotFound`].
 * The caller owns the result and must release it with
 * [`callbook_result_free`].
 *
 * # Safety
 *
 * `db` must be a valid pointer returned by [`callbook_open`]. `callsign` must
 * be a valid NUL-terminated UTF-8 C string. `out` must be a writable pointer
 * to `*mut callbook_lookup_result`.
 */
int callbook_lookup_modern(const struct callbook_db *db,
                           const char *callsign,
                           struct callbook_lookup_result **out);

/**
 * Free a result returned by [`callbook_lookup_modern`]. Safe to pass null.
 *
 * # Safety
 *
 * `result` must be null or a pointer returned by [`callbook_lookup_modern`]
 * that has not already been freed.
 */
void callbook_result_free(struct callbook_lookup_result *result);

/**
 * Return the normalized query string for a lookup result.
 *
 * The returned pointer is valid until [`callbook_result_free`] is called.
 *
 * # Safety
 *
 * `result` must be null or a valid pointer returned by
 * [`callbook_lookup_modern`] that has not been freed.
 */
const char *callbook_result_query(const struct callbook_lookup_result *result);

/**
 * Return the status of a lookup result.
 *
 * # Safety
 *
 * `result` must be null or a valid pointer returned by
 * [`callbook_lookup_modern`] that has not been freed.
 */
enum callbook_lookup_status callbook_result_status(const struct callbook_lookup_result *result);

/**
 * Return the current snapshot, or null when there is no current record.
 *
 * The returned pointer is borrowed from `result` and is valid until
 * [`callbook_result_free`] is called.
 *
 * # Safety
 *
 * `result` must be null or a valid pointer returned by
 * [`callbook_lookup_modern`] that has not been freed.
 */
const struct callbook_snapshot *callbook_result_current(const struct callbook_lookup_result *result);

/**
 * Return the number of historical snapshots in a lookup result.
 *
 * # Safety
 *
 * `result` must be a valid pointer returned by [`callbook_lookup_modern`] that
 * has not been freed.
 */
int callbook_result_history_len(const struct callbook_lookup_result *result);

/**
 * Return one historical snapshot by zero-based index, or null when out of range.
 *
 * The returned pointer is borrowed from `result` and is valid until
 * [`callbook_result_free`] is called.
 *
 * # Safety
 *
 * `result` must be null or a valid pointer returned by
 * [`callbook_lookup_modern`] that has not been freed.
 */
const struct callbook_snapshot *callbook_result_history_get(const struct callbook_lookup_result *result,
                                                            int index);

/**
 * Return a snapshot string field selected by [`callbook_modern_field`].
 *
 * Missing fields return an empty string. The returned pointer is borrowed
 * from the owning result and is valid until [`callbook_result_free`] is called.
 *
 * # Safety
 *
 * `snapshot` must be null or a pointer returned by
 * [`callbook_result_current`] / [`callbook_result_history_get`] whose owning
 * result has not been freed.
 */
const char *callbook_snapshot_field(const struct callbook_snapshot *snapshot, int field_id);

/**
 * Return the snapshot vintage year, or -1 for current/non-vintage records.
 *
 * # Safety
 *
 * `snapshot` must be null or a pointer returned by
 * [`callbook_result_current`] / [`callbook_result_history_get`] whose owning
 * result has not been freed.
 */
int callbook_snapshot_vintage(const struct callbook_snapshot *snapshot);

/**
 * Return ORed `CALLBOOK_SOURCE_*` flags for a snapshot.
 *
 * # Safety
 *
 * `snapshot` must be null or a pointer returned by
 * [`callbook_result_current`] / [`callbook_result_history_get`] whose owning
 * result has not been freed.
 */
uint32_t callbook_snapshot_source_flags(const struct callbook_snapshot *snapshot);

/**
 * Return the snapshot jurisdiction classification.
 *
 * # Safety
 *
 * `snapshot` must be null or a pointer returned by
 * [`callbook_result_current`] / [`callbook_result_history_get`] whose owning
 * result has not been freed.
 */
enum callbook_jurisdiction callbook_snapshot_jurisdiction(const struct callbook_snapshot *snapshot);

/**
 * Return the raw concatenated interest-code string.
 *
 * # Safety
 *
 * `snapshot` must be null or a pointer returned by
 * [`callbook_result_current`] / [`callbook_result_history_get`] whose owning
 * result has not been freed.
 */
const char *callbook_snapshot_interest_codes_raw(const struct callbook_snapshot *snapshot);

/**
 * Return the number of parsed interest codes.
 *
 * # Safety
 *
 * Same pointer requirements as [`callbook_snapshot_interest_codes_raw`].
 */
int callbook_snapshot_interest_code_len(const struct callbook_snapshot *snapshot);

/**
 * Return one parsed interest code by zero-based index.
 *
 * # Safety
 *
 * Same pointer requirements as [`callbook_snapshot_interest_codes_raw`].
 */
const char *callbook_snapshot_interest_code_get(const struct callbook_snapshot *snapshot,
                                                int index);

/**
 * Return the number of resolved interest labels.
 *
 * # Safety
 *
 * Same pointer requirements as [`callbook_snapshot_interest_codes_raw`].
 */
int callbook_snapshot_interest_len(const struct callbook_snapshot *snapshot);

/**
 * Return one resolved interest by zero-based index.
 *
 * # Safety
 *
 * Same pointer requirements as [`callbook_snapshot_interest_codes_raw`].
 */
const struct callbook_interest *callbook_snapshot_interest_get(const struct callbook_snapshot *snapshot,
                                                               int index);

/**
 * Return an interest's four-digit code.
 *
 * # Safety
 *
 * `interest` must be null or a pointer returned by
 * [`callbook_snapshot_interest_get`] whose owning result has not been freed.
 */
const char *callbook_interest_code(const struct callbook_interest *interest);

/**
 * Return an interest's category heading.
 *
 * # Safety
 *
 * Same pointer requirements as [`callbook_interest_code`].
 */
const char *callbook_interest_category(const struct callbook_interest *interest);

/**
 * Return an interest's human-readable label.
 *
 * # Safety
 *
 * Same pointer requirements as [`callbook_interest_code`].
 */
const char *callbook_interest_label(const struct callbook_interest *interest);

/**
 * Build a station profile for `callsign`.
 *
 * The returned profile owns all nested strings and borrowed child pointers.
 * Release it with [`callbook_profile_free`].
 *
 * # Safety
 *
 * `db` must be a valid pointer returned by [`callbook_open`]. `callsign` must
 * be a valid NUL-terminated UTF-8 string. `out` must be writable.
 */
int callbook_profile_for_callsign(const struct callbook_db *db,
                                  const char *callsign,
                                  struct callbook_profile **out);

/**
 * Free a profile returned by [`callbook_profile_for_callsign`]. Safe to pass null.
 *
 * # Safety
 *
 * `profile` must be null or a pointer returned by
 * [`callbook_profile_for_callsign`] that has not already been freed.
 */
void callbook_profile_free(struct callbook_profile *profile);

/**
 * Return the normalized callsign for a profile.
 *
 * # Safety
 *
 * `profile` must be null or a valid profile pointer.
 */
const char *callbook_profile_callsign(const struct callbook_profile *profile);

/**
 * Return the lookup status for a profile.
 *
 * # Safety
 *
 * `profile` must be null or a valid profile pointer.
 */
enum callbook_lookup_status callbook_profile_status(const struct callbook_profile *profile);

/**
 * Return the current snapshot in a profile, or null.
 *
 * # Safety
 *
 * `profile` must be null or a valid profile pointer.
 */
const struct callbook_snapshot *callbook_profile_current(const struct callbook_profile *profile);

/**
 * Return the number of historical snapshots summarized by the profile.
 *
 * # Safety
 *
 * `profile` must be null or a valid profile pointer.
 */
int callbook_profile_history_snapshot_count(const struct callbook_profile *profile);

/**
 * Return the number of unique history vintages in a profile.
 *
 * # Safety
 *
 * `profile` must be null or a valid profile pointer.
 */
int callbook_profile_history_vintage_len(const struct callbook_profile *profile);

/**
 * Return one unique profile history vintage, or -1 when out of range.
 *
 * # Safety
 *
 * `profile` must be null or a valid profile pointer.
 */
int callbook_profile_history_vintage_get(const struct callbook_profile *profile, int index);

/**
 * Return country metadata borrowed from a profile, or null.
 *
 * # Safety
 *
 * `profile` must be null or a valid profile pointer.
 */
const struct callbook_country_info *callbook_profile_country(const struct callbook_profile *profile);

/**
 * Return lookup-count metadata borrowed from a profile, or null.
 *
 * # Safety
 *
 * `profile` must be null or a valid profile pointer.
 */
const struct callbook_lookup_count *callbook_profile_lookup_count(const struct callbook_profile *profile);

/**
 * Return the number of assets attached to a profile.
 *
 * # Safety
 *
 * `profile` must be null or a valid profile pointer.
 */
int callbook_profile_asset_len(const struct callbook_profile *profile);

/**
 * Return one profile asset by zero-based index, or null.
 *
 * # Safety
 *
 * `profile` must be null or a valid profile pointer.
 */
const struct callbook_asset *callbook_profile_asset_get(const struct callbook_profile *profile,
                                                        int index);

/**
 * Look up country metadata for `callsign`.
 *
 * Release the returned object with [`callbook_country_info_free`].
 *
 * # Safety
 *
 * `db` must be a valid database pointer. `callsign` must be a valid
 * NUL-terminated UTF-8 string. `out` must be writable.
 */
int callbook_country_info_for_callsign(const struct callbook_db *db,
                                       const char *callsign,
                                       struct callbook_country_info **out);

/**
 * Free country metadata returned by [`callbook_country_info_for_callsign`].
 *
 * # Safety
 *
 * `country` must be null or an owned country pointer returned by this API.
 */
void callbook_country_info_free(struct callbook_country_info *country);

/**
 * Build an owned snapshot of the unified country catalog.
 *
 * Release the returned object with [`callbook_country_catalog_free`].
 *
 * # Safety
 *
 * `db` must be a valid database pointer and `out` must be writable.
 */
int callbook_country_catalog_open(const struct callbook_db *db,
                                  struct callbook_country_catalog **out);

/**
 * Free a country catalog returned by [`callbook_country_catalog_open`].
 *
 * # Safety
 *
 * `catalog` must be null or an owned country-catalog pointer.
 */
void callbook_country_catalog_free(struct callbook_country_catalog *catalog);

/**
 * Return the number of records in a country catalog snapshot.
 *
 * # Safety
 *
 * `catalog` must be null or a valid country-catalog pointer.
 */
int callbook_country_catalog_len(const struct callbook_country_catalog *catalog);

/**
 * Return one country catalog record by zero-based index, or null.
 *
 * # Safety
 *
 * `catalog` must be null or a valid country-catalog pointer.
 */
const struct callbook_country_info *callbook_country_catalog_get(const struct callbook_country_catalog *catalog,
                                                                 int index);

/**
 * Return the country display label.
 *
 * # Safety
 *
 * `country` must be null or a valid country pointer.
 */
const char *callbook_country_name(const struct callbook_country_info *country);

/**
 * Return the raw country label from the source sidecar.
 *
 * # Safety
 *
 * `country` must be null or a valid country pointer.
 */
const char *callbook_country_raw_name(const struct callbook_country_info *country);

/**
 * Return the cleaned country label.
 *
 * # Safety
 *
 * `country` must be null or a valid country pointer.
 */
const char *callbook_country_cleaned_name(const struct callbook_country_info *country);

/**
 * Return the country code, or an empty string.
 *
 * # Safety
 *
 * `country` must be null or a valid country pointer.
 */
const char *callbook_country_code(const struct callbook_country_info *country);

/**
 * Return the country jurisdiction classification.
 *
 * # Safety
 *
 * `country` must be null or a valid country pointer.
 */
enum callbook_jurisdiction callbook_country_jurisdiction(const struct callbook_country_info *country);

/**
 * Return the ITU zone, or -1 when absent.
 *
 * # Safety
 *
 * `country` must be null or a valid country pointer.
 */
int callbook_country_itu_zone(const struct callbook_country_info *country);

/**
 * Return the CQ zone, or -1 when absent.
 *
 * # Safety
 *
 * `country` must be null or a valid country pointer.
 */
int callbook_country_cq_zone(const struct callbook_country_info *country);

/**
 * Return the continent code, or an empty string.
 *
 * # Safety
 *
 * `country` must be null or a valid country pointer.
 */
const char *callbook_country_continent(const struct callbook_country_info *country);

/**
 * Write the country latitude to `out`; returns 0 when present.
 *
 * # Safety
 *
 * `country` must be a valid country pointer and `out` must be writable.
 */
int callbook_country_latitude(const struct callbook_country_info *country, double *out);

/**
 * Write the country longitude to `out`; returns 0 when present.
 *
 * # Safety
 *
 * `country` must be a valid country pointer and `out` must be writable.
 */
int callbook_country_longitude(const struct callbook_country_info *country, double *out);

/**
 * Return the numeric country code, or -1 when absent.
 *
 * # Safety
 *
 * `country` must be null or a valid country pointer.
 */
int callbook_country_numeric_code(const struct callbook_country_info *country);

/**
 * Return the source sidecar used for country metadata.
 *
 * # Safety
 *
 * `country` must be null or a valid country pointer.
 */
enum callbook_country_source callbook_country_source_value(const struct callbook_country_info *country);

/**
 * Look up web lookup-count metadata for a callsign.
 *
 * Release the returned object with [`callbook_lookup_count_free`].
 *
 * # Safety
 *
 * `db` must be a valid database pointer. `callsign` must be a valid
 * NUL-terminated UTF-8 string. `out` must be writable.
 */
int callbook_lookup_count_for_callsign(const struct callbook_db *db,
                                       const char *callsign,
                                       struct callbook_lookup_count **out);

/**
 * Free a lookup count returned by [`callbook_lookup_count_for_callsign`].
 *
 * # Safety
 *
 * `count` must be null or an owned lookup-count pointer returned by this API.
 */
void callbook_lookup_count_free(struct callbook_lookup_count *count);

/**
 * Build an owned snapshot of the searchable `counts.dat` catalog.
 *
 * Release the returned object with [`callbook_lookup_counts_catalog_free`].
 *
 * # Safety
 *
 * `db` must be a valid database pointer and `out` must be writable.
 */
int callbook_lookup_counts_catalog_open(const struct callbook_db *db,
                                        struct callbook_lookup_counts_catalog **out);

/**
 * Free a lookup-count catalog returned by [`callbook_lookup_counts_catalog_open`].
 *
 * # Safety
 *
 * `catalog` must be null or an owned lookup-count-catalog pointer.
 */
void callbook_lookup_counts_catalog_free(struct callbook_lookup_counts_catalog *catalog);

/**
 * Return the number of records in a lookup-count catalog snapshot.
 *
 * # Safety
 *
 * `catalog` must be null or a valid lookup-count-catalog pointer.
 */
int callbook_lookup_counts_catalog_len(const struct callbook_lookup_counts_catalog *catalog);

/**
 * Return one lookup-count catalog record by zero-based index, or null.
 *
 * # Safety
 *
 * `catalog` must be null or a valid lookup-count-catalog pointer.
 */
const struct callbook_lookup_count *callbook_lookup_counts_catalog_get(const struct callbook_lookup_counts_catalog *catalog,
                                                                       int index);

/**
 * Return the lookup-count key.
 *
 * # Safety
 *
 * `count` must be null or a valid lookup-count pointer.
 */
const char *callbook_lookup_count_key(const struct callbook_lookup_count *count);

/**
 * Return the HamCall.net lookup count.
 *
 * # Safety
 *
 * `count` must be null or a valid lookup-count pointer.
 */
uint32_t callbook_lookup_count_value(const struct callbook_lookup_count *count);

/**
 * Return the update date as `YYYYMMDD`, or -1 when absent.
 *
 * # Safety
 *
 * `count` must be null or a valid lookup-count pointer.
 */
int callbook_lookup_count_updated_yyyymmdd(const struct callbook_lookup_count *count);

/**
 * Return the count-record status byte as a string, or empty when absent.
 *
 * # Safety
 *
 * `count` must be null or a valid lookup-count pointer.
 */
const char *callbook_lookup_count_status(const struct callbook_lookup_count *count);

/**
 * Return an asset's kind.
 *
 * # Safety
 *
 * `asset` must be null or a valid asset pointer.
 */
enum callbook_asset_kind callbook_asset_kind_value(const struct callbook_asset *asset);

/**
 * Return an asset's callsign or country key.
 *
 * # Safety
 *
 * `asset` must be null or a valid asset pointer.
 */
const char *callbook_asset_key(const struct callbook_asset *asset);

/**
 * Return an asset's media type.
 *
 * # Safety
 *
 * `asset` must be null or a valid asset pointer.
 */
const char *callbook_asset_media_type(const struct callbook_asset *asset);

/**
 * Return an asset's on-disk path.
 *
 * # Safety
 *
 * `asset` must be null or a valid asset pointer.
 */
const char *callbook_asset_path(const struct callbook_asset *asset);

/**
 * Return the number of records in `usa.csv.zip`, or 0 when absent.
 *
 * # Safety
 *
 * `db` must be null or a valid database pointer.
 */
int callbook_current_us_record_count(const struct callbook_db *db);

/**
 * Return one current-US catalog record by sorted index.
 *
 * Release the returned object with [`callbook_us_record_free`].
 *
 * # Safety
 *
 * `db` must be a valid database pointer and `out` must be writable.
 */
int callbook_current_us_record_get(const struct callbook_db *db,
                                   int index,
                                   struct callbook_us_record **out);

/**
 * Look up one current-US catalog record by callsign.
 *
 * Release the returned object with [`callbook_us_record_free`].
 *
 * # Safety
 *
 * `db` must be a valid database pointer, `callsign` must be a valid
 * NUL-terminated UTF-8 string, and `out` must be writable.
 */
int callbook_current_us_lookup(const struct callbook_db *db,
                               const char *callsign,
                               struct callbook_us_record **out);

/**
 * Free a current-US record returned by this API. Safe to pass null.
 *
 * # Safety
 *
 * `record` must be null or an owned current-US record pointer.
 */
void callbook_us_record_free(struct callbook_us_record *record);

/**
 * Return one current-US record string field.
 *
 * # Safety
 *
 * `record` must be null or a valid current-US record pointer.
 */
const char *callbook_us_record_field(const struct callbook_us_record *record, int field_id);

/**
 * Return the number of interest-code definitions loaded from `ham0/interest`.
 *
 * # Safety
 *
 * `db` must be null or a valid database pointer.
 */
int callbook_interest_catalog_len(const struct callbook_db *db);

/**
 * Return one interest definition by catalog index.
 *
 * Release the returned object with [`callbook_interest_definition_free`].
 *
 * # Safety
 *
 * `db` must be a valid database pointer and `out` must be writable.
 */
int callbook_interest_catalog_get(const struct callbook_db *db,
                                  int index,
                                  struct callbook_interest_definition **out);

/**
 * Look up one interest-code definition.
 *
 * Release the returned object with [`callbook_interest_definition_free`].
 *
 * # Safety
 *
 * `db` must be a valid database pointer, `code` must be a valid
 * NUL-terminated UTF-8 string, and `out` must be writable.
 */
int callbook_interest_catalog_lookup(const struct callbook_db *db,
                                     const char *code,
                                     struct callbook_interest_definition **out);

/**
 * Free an owned interest definition. Safe to pass null.
 *
 * # Safety
 *
 * `definition` must be null or an owned definition pointer.
 */
void callbook_interest_definition_free(struct callbook_interest_definition *definition);

/**
 * Return an interest definition's code.
 *
 * # Safety
 *
 * `definition` must be null or a valid definition pointer.
 */
const char *callbook_interest_definition_code(const struct callbook_interest_definition *definition);

/**
 * Return an interest definition's category.
 *
 * # Safety
 *
 * `definition` must be null or a valid definition pointer.
 */
const char *callbook_interest_definition_category(const struct callbook_interest_definition *definition);

/**
 * Return an interest definition's label.
 *
 * # Safety
 *
 * `definition` must be null or a valid definition pointer.
 */
const char *callbook_interest_definition_label(const struct callbook_interest_definition *definition);

/**
 * Search decoded records for a four-digit interest code.
 *
 * Release the returned object with [`callbook_interest_search_free`].
 *
 * # Safety
 *
 * `db` must be a valid database pointer, `code` must be a valid
 * NUL-terminated UTF-8 string, and `out` must be writable.
 */
int callbook_interest_search_for_code(const struct callbook_db *db,
                                      const char *code,
                                      struct callbook_interest_search_result **out);

/**
 * Free an interest search returned by [`callbook_interest_search_for_code`].
 *
 * # Safety
 *
 * `search` must be null or an owned interest-search pointer.
 */
void callbook_interest_search_free(struct callbook_interest_search_result *search);

/**
 * Return the normalized interest-search code.
 *
 * # Safety
 *
 * `search` must be null or a valid interest-search pointer.
 */
const char *callbook_interest_search_code(const struct callbook_interest_search_result *search);

/**
 * Return the definition for this interest search, or null.
 *
 * # Safety
 *
 * `search` must be null or a valid interest-search pointer.
 */
const struct callbook_interest_definition *callbook_interest_search_definition(const struct callbook_interest_search_result *search);

/**
 * Return the number of interest-search matches.
 *
 * # Safety
 *
 * `search` must be null or a valid interest-search pointer.
 */
int callbook_interest_search_match_len(const struct callbook_interest_search_result *search);

/**
 * Return one interest-search match by zero-based index, or null.
 *
 * # Safety
 *
 * `search` must be null or a valid interest-search pointer.
 */
const struct callbook_interest_search_match *callbook_interest_search_match_get(const struct callbook_interest_search_result *search,
                                                                                int index);

/**
 * Return the callsign for an interest-search match.
 *
 * # Safety
 *
 * `entry` must be null or a valid match pointer.
 */
const char *callbook_interest_search_match_callsign(const struct callbook_interest_search_match *entry);

/**
 * Return the archive vintage for an interest-search match, or -1 for current.
 *
 * # Safety
 *
 * `entry` must be null or a valid match pointer.
 */
int callbook_interest_search_match_vintage(const struct callbook_interest_search_match *entry);

/**
 * Render the default station map SVG into `out_buf`.
 *
 * Returns the number of bytes written, excluding NUL. Use
 * [`callbook_map_svg_required_len`] to size the output buffer.
 *
 * # Safety
 *
 * `db` must be a valid database pointer, `callsign` must be a valid
 * NUL-terminated UTF-8 string, and `out_buf` must be writable.
 */
int callbook_map_svg(const struct callbook_db *db,
                     const char *callsign,
                     char *out_buf,
                     int out_buf_len);

/**
 * Return the required buffer length for [`callbook_map_svg`], including NUL.
 *
 * # Safety
 *
 * `db` must be a valid database pointer and `callsign` must be a valid
 * NUL-terminated UTF-8 string.
 */
int callbook_map_svg_required_len(const struct callbook_db *db, const char *callsign);

/**
 * Look up `callsign` and write the structured result as JSON.
 *
 * Returns the number of bytes written, excluding the trailing NUL. A
 * not-found callsign writes a JSON object with `"status": "NotFound"` and
 * still returns success. Use [`callbook_lookup_json_required_len`] to size
 * the output buffer.
 *
 * # Safety
 *
 * `db` must be null or a pointer returned by [`callbook_open`]. `callsign`
 * must be a valid NUL-terminated UTF-8 string. `out_buf` must be writable
 * for `out_buf_len` bytes.
 */
int callbook_lookup_json(const struct callbook_db *db,
                         const char *callsign,
                         char *out_buf,
                         int out_buf_len);

/**
 * Return the buffer size required for [`callbook_lookup_json`], including NUL.
 *
 * # Safety
 *
 * `db` must be null or a pointer returned by [`callbook_open`]. `callsign`
 * must be a valid NUL-terminated UTF-8 string.
 */
int callbook_lookup_json_required_len(const struct callbook_db *db, const char *callsign);

/**
 * Crate version string (NUL-terminated, static).
 */
const char *callbook_version(void);

/**
 * Map a negative return code from any of the `callbook_*` functions to a
 * short, human-readable, NUL-terminated, statically-allocated description.
 *
 * Returns a pointer to `"unknown error"` for codes that are not recognised,
 * and `"ok"` for non-negative inputs (which are not errors).
 */
const char *callbook_strerror(int code);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CALLBOOK_H */
